import os
os.system("apt install python")
os.system("apt install python3-pip")
os.system("apt install git")
os.system("apt install perl")
os.system("apt install grep")
os.system("apt install steghide")
os.system("pip3 install bs4")
os.system("pip3 install threaded")
os.system("pip3 install requests")
os.system("pip3 install mechanize")
os.system("git clone https://github.com/sullo/nikto")
